
# 【正常填报】所需信息
[daily]
ljsjcs = "否"       # 7日内是否有中高风险地区旅居史、接触史
sqsb = "是"       # 是否按照要求向学校、社区及时上报
sfgl = "否"       # 是否隔离观察
sfys = "否"       # 是否身体有疑似典型症状
sffr = "否"       # 是否发热
other = ""        # 其他信息
tiwen = ""        # 体温(早) (留空随机)
tiwen1 = ""       # 体温(中) (留空随机，输入0保留上一次填报数值)
tiwen2 = ""       # 体温(晚) (留空随机，输入0保留上一次填报数值)





# 【填报必要信息】
[userinfo]
# Github Actions用户请注意！请将该片段以"USERINFO"命名并保存至Secrets内，防止个人信息泄露！
# =================== 片段起始 ===================

userid = ""       # 学工号（学号）
uid = ""        # 个人UID（通过抓包获取）

# =================== 片段终止 ===================





# 【坐标信息】，留空将使用【其他信息】完成填表
# 使用【坐标信息】进行填报将会自动启用填报结果检查
[location]
# Github Actions用户请注意！请将该片段以"LOCATION"命名并保存至Secrets内，防止个人信息泄露！
# =================== 片段起始 ===================

latitude = ""      # 纬度
longitude = ""       # 经度
accuracy = ""       # 精度（留空默认为15）

# =================== 片段终止 ===================





# 【其他信息】，仅在【坐标信息】无法使用时启用
[other]
# Github Actions用户请注意！请将该片段以"OTHER"命名并保存至Secrets内，防止个人信息泄露！
# =================== 片段起始 ===================

xingming = ""       # 姓名
shoujihao = ""        # 手机号
dwyx = ""       # 单位院系
shengfen = ""       # 当前所在省份
chengshi = ""       # 所在城市
# +++++++++++++++++++++++++++++++++++++++++++++++
lsqx = ""       # 离沈去向
# 【离沈去向】为强制覆盖条目，当【所在城市】不为【沈阳市】，并且本条目不为空，本条目将会强制启用
# 本条目在启用【坐标信息】后依然会进行覆盖，若本条目为空，则【离沈去向】将与【所在城市】相同
# +++++++++++++++++++++++++++++++++++++++++++++++

# =================== 片段终止 ===================





# 【体温配置】
[temperature]
min = 36.0      # 随机体温最小值
max = 36.9      # 随机体温最大值





# 【脚本设置】
[settings]
try_times = 3       # 失败重试次数
debug = 0       # 开启调试，调试信息将通过推送发送

# 推送配置
# 敬请期待~~~
